sqlalchemy.exc.NoForeignKeysError
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship GroupFoodOrder.individual_orders - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.

Traceback (most recent call last)
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2437, in _determine_joins
self.primaryjoin = join_condition(
                   
File "E:\anaconda\Lib\site-packages\sqlalchemy\sql\util.py", line 123, in join_condition
return Join._join_condition(
       
File "E:\anaconda\Lib\site-packages\sqlalchemy\sql\selectable.py", line 1443, in _join_condition
raise exc.NoForeignKeysError(
^
The above exception was the direct cause of the following exception:
File "E:\anaconda\Lib\site-packages\flask\app.py", line 1536, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\werkzeug\middleware\proxy_fix.py", line 183, in __call__
return self.app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\flask\app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "c:\Users\Hemanth\OneDrive\Desktop\projects\PBL Project\RailServe\main.py", line 12, in index
running_trains = get_running_trains()
                 ^^^^^^^^^^^^^^^^^^^^
File "c:\Users\Hemanth\OneDrive\Desktop\projects\PBL Project\RailServe\src\utils.py", line 8, in get_running_trains
return Train.query.filter_by(active=True).all()
       ^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\flask_sqlalchemy\model.py", line 22, in __get__
return cls.query_class(
       
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
self._set_entities(entities)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
coercions.expect(
^
File "E:\anaconda\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
insp._post_inspect
^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1257, in __get__
obj.__dict__[self.__name__] = result = self.fget(obj)
                                       ^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
self._check_configure()
^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
_configure_registries({self.registry}, cascade=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
_do_configure_registries(registries, cascade)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
mapper._post_configure_properties()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
prop.init()
^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
self.do_init()
^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1658, in do_init
self._setup_join_conditions()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1898, in _setup_join_conditions
self._join_condition = jc = JoinCondition(
                            
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2324, in __init__
self._determine_joins()
^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2458, in _determine_joins
raise sa_exc.NoForeignKeysError(
^^^^^^^^^^
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship GroupFoodOrder.individual_orders - there are no foreign keys linking these tables. Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
